require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Lint:
  Severity: error

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 25

Metrics/ParameterLists:
  Max: 10
  MaxOptionalParameters: 5

Metrics/AbcSize:
  Max: 70

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 60

Layout/LineLength:
  Max: 150

Naming/MethodParameterName:
  MinNameLength: 2

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
