module Growthbook
  # Utils for working with encrypted feature payloads.
  class DecryptionUtil
    # @return [String, nil] The decrypted payload, or nil if it fails to decrypt
    def self.decrypt: (String payload, key: String) -> String?
  end
end
